export const C = {
  page: { minHeight: "100vh", background: "#f9f8f7", fontFamily: "'DM Sans','Helvetica Neue',sans-serif", color: "#1c1c1c" },
  nav: { background: "#fff", borderBottom: "1px solid #eae8e4", padding: "0 2rem", height: 58, display: "flex", alignItems: "center", justifyContent: "space-between", position: "sticky", top: 0, zIndex: 200 },
  brand: { fontSize: 17, fontWeight: 700, letterSpacing: "-0.03em", cursor: "pointer", color: "#1c1c1c" },
  navLink: (active) => ({ background: active ? "#f0ede8" : "none", border: "none", padding: "6px 13px", borderRadius: 6, fontSize: 13, fontWeight: active ? 600 : 400, color: active ? "#1c1c1c" : "#666", cursor: "pointer" }),
  btnPrimary: { background: "#1c1c1c", color: "#fff", border: "none", padding: "9px 18px", borderRadius: 7, fontSize: 13, fontWeight: 500, cursor: "pointer" },
  btnSm: { background: "#1c1c1c", color: "#fff", border: "none", padding: "6px 13px", borderRadius: 6, fontSize: 12, fontWeight: 500, cursor: "pointer" },
  btnOutline: { background: "#fff", color: "#1c1c1c", border: "1px solid #ddd", padding: "6px 13px", borderRadius: 6, fontSize: 12, fontWeight: 500, cursor: "pointer" },
  btnDanger: { background: "#fff", color: "#c0392b", border: "1px solid #f5c6cb", padding: "6px 13px", borderRadius: 6, fontSize: 12, fontWeight: 500, cursor: "pointer" },
  btnGhost: { background: "none", border: "none", color: "#888", fontSize: 16, cursor: "pointer", padding: "4px 8px" },
  main: { maxWidth: 1120, margin: "0 auto", padding: "2.5rem 2rem" },
  card: { background: "#fff", border: "1px solid #eae8e4", borderRadius: 12, padding: "1.5rem" },
  cardSm: { background: "#fff", border: "1px solid #eae8e4", borderRadius: 10, padding: "1.25rem" },
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.03em", margin: "0 0 4px" },
  h2: { fontSize: 16, fontWeight: 600, letterSpacing: "-0.02em", margin: "0 0 1.25rem" },
  label: { fontSize: 11, fontWeight: 600, color: "#888", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 5, display: "block" },
  input: { width: "100%", padding: "9px 11px", border: "1px solid #ddd", borderRadius: 7, fontSize: 13, color: "#1c1c1c", background: "#fff", outline: "none", boxSizing: "border-box" },
  textarea: { width: "100%", padding: "9px 11px", border: "1px solid #ddd", borderRadius: 7, fontSize: 13, color: "#1c1c1c", background: "#fff", outline: "none", boxSizing: "border-box", resize: "vertical", minHeight: 72 },
  err: { background: "#fef2f2", color: "#991b1b", border: "1px solid #fecaca", borderRadius: 7, padding: "9px 13px", fontSize: 12, marginTop: 8 },
  ok:  { background: "#f0fdf4", color: "#166534", border: "1px solid #bbf7d0", borderRadius: 7, padding: "9px 13px", fontSize: 12, marginTop: 8 },
  divider: { height: 1, background: "#eae8e4", margin: "1rem 0" },
  empty: { textAlign: "center", padding: "4rem 1rem", color: "#bbb", fontSize: 13 },
  grid3: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))", gap: "1.1rem" },
  badge: (c) => ({
    display: "inline-block", padding: "2px 8px", borderRadius: 4, fontSize: 11, fontWeight: 600,
    background: c==="green"?"#ecfdf5":c==="red"?"#fef2f2":c==="blue"?"#eff6ff":c==="amber"?"#fffbeb":"#f5f5f4",
    color:      c==="green"?"#166534":c==="red"?"#991b1b":c==="blue"?"#1d4ed8":c==="amber"?"#92400e":"#57534e",
  }),
  tag: { fontSize: 11, color: "#888", background: "#f3f2f0", borderRadius: 4, padding: "2px 7px", display: "inline-block" },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,.4)", zIndex: 300, display: "flex", alignItems: "center", justifyContent: "center" },
  modalBox: { background: "#fff", borderRadius: 14, padding: "2rem", width: 460, maxWidth: "90vw", maxHeight: "85vh", overflowY: "auto" },
};
